import { ApolloWrapper, AuthWrapper } from '@nx-nextjs-tailwind-storybook/feature'
import './styles.css'
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

import { MantineProvider, ColorSchemeScript } from '@mantine/core';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {

  return (
    <html lang={params.lang} className='light'>
      <head><ColorSchemeScript /></head>
      <body className='font-sans'>
        <ApolloWrapper>
          <MantineProvider>
            <AuthWrapper>
              {children}
            </AuthWrapper>
          </MantineProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
