import { ApolloWrapper } from '@nx-nextjs-tailwind-storybook/feature'
import '../styles.css'
import '@mantine/core/styles.css';
import MantineProviderWrapper from 'libs/feature/src/lib/MantineProvider'
import MainLayout from 'libs/ui/src/lib/MainLayout/MainLayout'
import links, { bottomLinks } from './links';
import { NavLink } from '@mantine/core';
import Link from 'next/link';
import { cookies } from 'next/headers';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
  }) {
  const authToken = cookies().get('authToken')

  const navItems = links.map(({ name, link, icon }) => {
    return <NavLink key={link} component={Link} href={link} label={name} leftSection={icon} />
  })
  const bottomNavItems = bottomLinks.map(({ name, link, icon }) => {
    return <NavLink key={link} component={Link} href={link} label={name} leftSection={icon} />
  })

  return (
    <ApolloWrapper authToken={authToken?.value as string}>
      <MantineProviderWrapper>
        <MainLayout
          navItems={navItems}
          bottomNavItems={bottomNavItems}
          {...{ logo: 'https://i.pinimg.com/originals/82/c6/5b/82c65b9bb0a75026fc4c82a438b4cc9b.jpg', }}
        >
          {children}
        </MainLayout>
      </MantineProviderWrapper>
    </ApolloWrapper>
  )
}
