import { getClient } from '@nx-nextjs-tailwind-storybook/feature'
import { PingDocument } from '@nx-nextjs-tailwind-storybook/data-access'
import '../styles.css'
import '@mantine/core/styles.css';
import MantineProviderWrapper from 'libs/feature/src/lib/MantineProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  const { data } = await getClient().query({ query: PingDocument })
  console.log({ data })
  return (
    <html lang={params.lang} className='light'>
      <body className='font-sans'>
        <MantineProviderWrapper>
          {children}
        </MantineProviderWrapper>
      </body>
    </html>
  )
}
